# Generated by Django 3.2.11 on 2022-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='api.IngredientQuantity', verbose_name='Ингредиенты'),
        ),
    ]
