### Получение всех тегов не авторизованным пользователем

GET http://127.0.0.1:8000/api/tags/

### Получение тега не авторизованным пользователем

GET http://127.0.0.1:8000/api/tags/1/

### Получение всех рецептов не авторизованным пользователем

GET http://127.0.0.1:8000/api/recipes/

### Получение рецепта не авторизованным пользователем

GET http://127.0.0.1:8000/api/recipes/1/

### Создание рецепта не авторизованным пользователем

POST http://127.0.0.1:8000/api/recipes/

{
  "ingredients": [
    {
      "id": 18627,
      "amount": 10
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

### Обновление рецепта не авторизованным пользователем

PATCH http://127.0.0.1:8000/api/recipes/1/

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 10
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

### Удаление рецепта не авторизованным пользователем

DELETE http://127.0.0.1:8000/api/recipes/1/

### Добавить рецепт в избранное не авторизованным пользователем

POST http://127.0.0.1:8000/api/recipes/1/favorite/

### Удалить рецепт из избранного не авторизованным пользователем

DELETE http://127.0.0.1:8000/api/recipes/1/favorite/

### Список покупок не авторизованным пользователем

GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/

### Добавить в список покупок не авторизованным пользователем

POST http://127.0.0.1:8000/api/recipes/1/download_shopping_cart/


### Удалить из списка покупок не авторизованным пользователем

DELETE http://127.0.0.1:8000/api/recipes/1/download_shopping_cart/

### Получение ингредиентов не авторизованным пользователем

GET http://127.0.0.1:8000/api/ingredients/

### Получение ингредиента не авторизованным пользователем

GET http://127.0.0.1:8000/api/ingredients/18627/

### Получение всех пользователей не авторизованным пользователем

GET http://127.0.0.1:8000/api/users/

### Профиль пользователя не авторизованным пользователем

GET http://127.0.0.1:8000/api/users/4/

### Профиль пользователя не авторизованным пользователем

GET http://127.0.0.1:8000/api/users/4/

### Текущий пользователь не авторизованным пользователем

GET http://127.0.0.1:8000/api/users/me/

### Изменение пароля не авторизованным пользователем

POST http://127.0.0.1:8000/api/users/set_password/

{
  "new_password": "efa2c0f585",
  "current_password": "efa2c0f585"
}

### Удаление токена не авторизованным пользователем

POST http://127.0.0.1:8000/api/auth/token/logout/

### Регистрация пользователя

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "vasya@yandex.ru",
  "username": "vasya",
  "first_name": "Вася",
  "last_name": "Пупкин",
  "password": "Dg4j13b9"
}

### Получение токена авторизованным пользователем

POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "username": "vasya",
  "password": "efa2c0f585"
}

### Удаление токена авторизованным пользователем

POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49


### Получение всех тегов авторизованным пользователем

GET http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Получение тега авторизованным пользователем

GET http://127.0.0.1:8000/api/tags/1/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Получение всех рецептов авторизованным пользователем

GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Получение рецепта авторизованным пользователем

GET http://127.0.0.1:8000/api/recipes/1/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Создание рецепта авторизованным пользователем

POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

{
  "ingredients": [
    {
      "id": 18627,
      "amount": 10
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

### Обновление рецепта авторизованным пользователем

PATCH http://127.0.0.1:8000/api/recipes/1/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 10
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

### Удаление рецепта авторизованным пользователем

DELETE http://127.0.0.1:8000/api/recipes/1/

### Получение ингредиентов авторизованным пользователем

GET http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Получение ингредиента авторизованным пользователем

GET http://127.0.0.1:8000/api/ingredients/18627/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Получение всех пользователей авторизованным пользователем

GET http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Профиль пользователя авторизованным пользователем

GET http://127.0.0.1:8000/api/users/4/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Текущий пользователь авторизованным пользователем

GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Изменение пароля авторизованным пользователем

POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

{
  "new_password": "efa2c0f585",
  "current_password": "Dg4j13b9"
}

### Список покупок авторизованным пользователем

GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Список покупок авторизованным пользователем

POST http://127.0.0.1:8000/api/recipes/1/download_shopping_cart/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Удалить из списка покупок авторизованным пользователем

DELETE http://127.0.0.1:8000/api/recipes/1/download_shopping_cart/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Добавить рецепт в избранное авторизованным пользователем

POST http://127.0.0.1:8000/api/recipes/1/favorite/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Удалить рецепт из избранного авторизованным пользователем

DELETE http://127.0.0.1:8000/api/recipes/1/favorite/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Мои подписки

GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Подписаться на пользователя

POST http://127.0.0.1:8000/api/users/1/subscriptions/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49

### Отписаться от пользователя

DELETE http://127.0.0.1:8000/api/users/1/subscriptions/
Content-Type: application/json
Authorization: token a29cedf4d8a64eaeffff86ddc4ea97f00f8efc49
